加载数据集

准备数据

In [2]:
data = [['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
                   ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
                   ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
                   ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
                   ['mr', 'licks', 'ate', 'my', 'steak',
                       'how', 'to', 'stop', 'him'],
                   ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']]
labels = [0, 1, 0, 1, 0, 1]
data,labels

([['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
  ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
  ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
  ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
  ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
  ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']],
 [0, 1, 0, 1, 0, 1])

创建单词表

In [3]:
vocab_set = set([])
for d in data:
    vocab_set = vocab_set | set(d)
vocab = list(vocab_set)
print(vocab[:10])
print(vocab.__len__())

['flea', 'has', 'my', 'to', 'food', 'stop', 'take', 'dalmation', 'is', 'licks']
32


创建词向量矩阵

将文本数据转换为数值向量，以便后续的机器学习算法可以处理。

In [4]:
train_data = []
def vectorize(vocab, da):
    vector = [0] * len(vocab)
    for d in da:
        if d in vocab:
            vector[vocab.index(d)] = 1
    return vector
    
for d in data:
    train_data.append(vectorize(vocab,d))

In [5]:
import numpy as np
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

训练贝叶斯

In [6]:
X_train,y_train = train_data,labels
print(X_train)
vocab_num = len(X_train[0])
# 拉普拉斯平滑处理
spam_num = np.ones(vocab_num)
ham_num = np.ones(vocab_num)
spam_sum = 2
ham_sum = 2
# 先验概率，在训练集中，侮辱类的概率
p_a = sum(y_train) / len(y_train)
for i in range(len(X_train)):
    if y_train[i] == 0:
        # 统计非侮辱类的相关单词频数
        ham_sum += 1
        ham_num += X_train[i]
    else:
        # 统计侮辱类的相关单词频数
        spam_sum += 1
        spam_num += X_train[i]
# 计算非侮辱类的条件概率
# 就是在非侮辱类中，每个单词出现的概率
p_ham = ham_num / ham_sum
# 计算侮辱类的条件概率
# 就是在侮辱类中，每个单词出现的概率
p_spam = spam_num / spam_sum
p_a,p_ham,p_spam

[[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1], [0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1], [0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1]]


(0.5,
 array([0.4, 0.4, 0.8, 0.4, 0.2, 0.4, 0.2, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4,
        0.4, 0.4, 0.2, 0.4, 0.4, 0.4, 0.4, 0.4, 0.6, 0.4, 0.4, 0.2, 0.2,
        0.2, 0.2, 0.2, 0.2, 0.2, 0.2]),
 array([0.2, 0.2, 0.2, 0.4, 0.4, 0.4, 0.4, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,
        0.2, 0.2, 0.4, 0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.6, 0.2, 0.4, 0.4,
        0.6, 0.4, 0.4, 0.4, 0.4, 0.8]))

测试数据

In [7]:
test1 = ['love', 'my', 'dalmation']
test2 = ['stupid', 'garbage', 'love']
test1_vocab = np.array(vectorize(vocab, test1))
test2_vocab = np.array(vectorize(vocab, test2))
test1_vocab

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

分类方法

In [8]:
def classify(test_data):
    ham_score = np.prod(np.power(p_ham,test_data))  * p_a
    spam_score = np.prod(np.power(p_spam,test_data)) * (1-p_a)
    return ("侮辱" if ham_score <= spam_score else "非侮辱",
    ham_score, spam_score)

In [9]:
result1 = classify(test1_vocab)
result2 = classify(test2_vocab)
result1,result2

(('非侮辱', np.float64(0.06400000000000002), np.float64(0.004000000000000001)),
 ('侮辱', np.float64(0.008000000000000002), np.float64(0.03200000000000001)))

在实际计算中，我们并未计算分母的全概率，因为两个类别的分母是相同的

## SKLearn实现

导库

In [10]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

准备数据

In [11]:
data = [' '.join(d) for d in data]
labels = [0, 1, 0, 1, 0, 1]
X_train, X_test, y_train, y_test = train_test_split(
    data, labels, test_size=0.2, random_state=42)

使用CountVectorizer将文本数据转换为词频矩阵

In [12]:
vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

训练模型

In [13]:
# 使用MultinomialNB训练模型
clf = MultinomialNB()
clf.fit(X_train_vec, y_train)

MultinomialNB()

预测测试集

In [14]:
y_pred = clf.predict(X_test_vec)
# 计算准确率
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 1.0


In [16]:
test1 = ['love', 'my', 'dalmation']
test2 = ['stupid', 'garbage', 'love']
test1_vec = vectorizer.transform([' '.join(test1)])
test2_vec = vectorizer.transform([' '.join(test2)])
result1 = clf.predict(test1_vec)
result2 = clf.predict(test2_vec)
result1,result2

(array([0]), array([1]))