## 自定义实现交叉验证

In [18]:
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

In [19]:
iris = load_iris()
X = iris.data
y = iris.target
k = 5  # number of folds
n_samples = X.shape[0]  # number of samples
fold_size = n_samples // k  # size of each fold
knn = KNeighborsClassifier(n_neighbors=k)
scores = []  # to store the scores for each fold
indices = np.random.permutation(n_samples)  # shuffle the indices
indices

array([106,  40,  59,  70,  15,  37,  54, 116,   3,  69, 105,  97,  86,
        18,  14,  76,  44, 112,  79,  26, 104,  24, 101,  32,  30,  65,
       117, 146,  75,  68, 140,  62,  66,  27, 114,  95,  23, 148,  22,
        53,  42, 137,  92,  55, 122,  10, 136,  35,  74,  56,  47, 130,
       143,  12,  58, 126, 120,  39,  94,  46, 100,  63, 134,  61,   0,
       103,  34,  89,  99,   6,  64,  78,  96,  13,  49,  67,  38, 145,
       124,  45, 127, 132, 144,  71,  60, 110,   2,  20,  16, 142,  57,
       119,   5,  93, 113, 147,  19,  85,  11,  83, 138, 107,  43,   8,
        72,  90,  50,  91,  84, 123,  82, 141,  33, 108,  29,  51, 102,
        52, 128,   7, 111,  36,  87,  28, 109, 129, 115,  98, 118,   4,
       125,  17,   9, 121,  77,  48,  21,  31,  25,  88,  80,  73, 133,
        41, 149, 131, 139,  81,   1, 135], dtype=int32)

将数据集划分为k个折叠

In [20]:
folds = [indices[i*fold_size:(i+1)*fold_size] for i in range(k)]
folds

[array([106,  40,  59,  70,  15,  37,  54, 116,   3,  69, 105,  97,  86,
         18,  14,  76,  44, 112,  79,  26, 104,  24, 101,  32,  30,  65,
        117, 146,  75,  68], dtype=int32),
 array([140,  62,  66,  27, 114,  95,  23, 148,  22,  53,  42, 137,  92,
         55, 122,  10, 136,  35,  74,  56,  47, 130, 143,  12,  58, 126,
        120,  39,  94,  46], dtype=int32),
 array([100,  63, 134,  61,   0, 103,  34,  89,  99,   6,  64,  78,  96,
         13,  49,  67,  38, 145, 124,  45, 127, 132, 144,  71,  60, 110,
          2,  20,  16, 142], dtype=int32),
 array([ 57, 119,   5,  93, 113, 147,  19,  85,  11,  83, 138, 107,  43,
          8,  72,  90,  50,  91,  84, 123,  82, 141,  33, 108,  29,  51,
        102,  52, 128,   7], dtype=int32),
 array([111,  36,  87,  28, 109, 129, 115,  98, 118,   4, 125,  17,   9,
        121,  77,  48,  21,  31,  25,  88,  80,  73, 133,  41, 149, 131,
        139,  81,   1, 135], dtype=int32)]

In [21]:
for i in range(k):
    test_indices = folds[i]
    train_indices = np.concatenate([folds[j]
                                   for j in range(k) if j != i], axis=0)
    X_train, y_train = X[train_indices], y[train_indices]
    X_test, y_test = X[test_indices], y[test_indices]
    knn.fit(X_train, y_train)
    score = knn.score(X_test, y_test)
    scores.append(score)
scores

[0.9333333333333333, 1.0, 1.0, 0.9333333333333333, 1.0]

## SKLearn工具包中的实现

In [22]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(knn, X, y, cv=k)
scores

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])